# TCL File Generated by Component Editor 17.1
# Mon Aug 28 10:29:43 MYT 2017
# DO NOT MODIFY


# 
# aso_splitter "aso_splitter" v1.0
#  2017.08.28.10:29:43
# aso splitter
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module aso_splitter
# 
set_module_property DESCRIPTION "aso splitter"
set_module_property NAME aso_splitter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "User Logic"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME aso_splitter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL aso_splitter
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property quartus_synth ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aso_splitter.v VERILOG PATH ../aso_splitter.v TOP_LEVEL_FILE

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property sim_verilog ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aso_splitter.v VERILOG PATH ../aso_splitter.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_st
# 
add_interface clock_st clock end
set_interface_property clock_st clockRate 0
set_interface_property clock_st ENABLED true
set_interface_property clock_st EXPORT_OF ""
set_interface_property clock_st PORT_NAME_MAP ""
set_interface_property clock_st CMSIS_SVD_VARIABLES ""
set_interface_property clock_st SVD_ADDRESS_GROUP ""

add_interface_port clock_st clk clk Input 1


# 
# connection point clock_st_reset
# 
add_interface clock_st_reset reset end
set_interface_property clock_st_reset associatedClock clock_st
set_interface_property clock_st_reset synchronousEdges DEASSERT
set_interface_property clock_st_reset ENABLED true
set_interface_property clock_st_reset EXPORT_OF ""
set_interface_property clock_st_reset PORT_NAME_MAP ""
set_interface_property clock_st_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_st_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_st_reset reset reset Input 1


# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clock_st
set_interface_property sink associatedReset clock_st_reset
set_interface_property sink dataBitsPerSymbol 8
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF ""
set_interface_property sink PORT_NAME_MAP ""
set_interface_property sink CMSIS_SVD_VARIABLES ""
set_interface_property sink SVD_ADDRESS_GROUP ""

add_interface_port sink asi_sink_data data Input 32
add_interface_port sink asi_sink_ready ready Output 1
add_interface_port sink asi_sink_valid valid Input 1
add_interface_port sink asi_sink_error error Input 6
add_interface_port sink asi_sink_startofpacket startofpacket Input 1
add_interface_port sink asi_sink_endofpacket endofpacket Input 1
add_interface_port sink asi_sink_empty empty Input 2


# 
# connection point source0
# 
add_interface source0 avalon_streaming start
set_interface_property source0 associatedClock clock_st
set_interface_property source0 associatedReset clock_st_reset
set_interface_property source0 dataBitsPerSymbol 8
set_interface_property source0 errorDescriptor ""
set_interface_property source0 firstSymbolInHighOrderBits true
set_interface_property source0 maxChannel 0
set_interface_property source0 readyLatency 0
set_interface_property source0 ENABLED true
set_interface_property source0 EXPORT_OF ""
set_interface_property source0 PORT_NAME_MAP ""
set_interface_property source0 CMSIS_SVD_VARIABLES ""
set_interface_property source0 SVD_ADDRESS_GROUP ""

add_interface_port source0 aso_source0_data data Output 32
add_interface_port source0 aso_source0_ready ready Input 1
add_interface_port source0 aso_source0_valid valid Output 1
add_interface_port source0 aso_source0_error error Output 6
add_interface_port source0 aso_source0_startofpacket startofpacket Output 1
add_interface_port source0 aso_source0_endofpacket endofpacket Output 1
add_interface_port source0 aso_source0_empty empty Output 2


# 
# connection point source1
# 
add_interface source1 avalon_streaming start
set_interface_property source1 associatedClock clock_st
set_interface_property source1 associatedReset clock_st_reset
set_interface_property source1 dataBitsPerSymbol 8
set_interface_property source1 errorDescriptor ""
set_interface_property source1 firstSymbolInHighOrderBits true
set_interface_property source1 maxChannel 0
set_interface_property source1 readyLatency 0
set_interface_property source1 ENABLED true
set_interface_property source1 EXPORT_OF ""
set_interface_property source1 PORT_NAME_MAP ""
set_interface_property source1 CMSIS_SVD_VARIABLES ""
set_interface_property source1 SVD_ADDRESS_GROUP ""

add_interface_port source1 aso_source1_data data Output 32
add_interface_port source1 aso_source1_ready ready Input 1
add_interface_port source1 aso_source1_valid valid Output 1
add_interface_port source1 aso_source1_error error Output 6
add_interface_port source1 aso_source1_startofpacket startofpacket Output 1
add_interface_port source1 aso_source1_endofpacket endofpacket Output 1
add_interface_port source1 aso_source1_empty empty Output 2

