# TCL File Generated by Component Editor 17.1
# Mon Aug 28 10:30:44 MYT 2017
# DO NOT MODIFY


# 
# error_adapter2 "error_adapter2" v1.0
#  2017.08.28.10:30:44
# 32 bits error adapter
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module error_adapter2
# 
set_module_property DESCRIPTION "32 bits error adapter"
set_module_property NAME error_adapter2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "User Logic"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME error_adapter2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL error_adapter2
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property quartus_synth ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file error_adapter2.v VERILOG PATH ../error_adapter2.v TOP_LEVEL_FILE

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property sim_verilog ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file error_adapter2.v VERILOG PATH ../error_adapter2.v


# 
# parameters
# 
add_parameter data_width INTEGER 32
set_parameter_property data_width DEFAULT_VALUE 32
set_parameter_property data_width DISPLAY_NAME data_width
set_parameter_property data_width TYPE INTEGER
set_parameter_property data_width UNITS None
set_parameter_property data_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property data_width AFFECTS_GENERATION false
set_parameter_property data_width HDL_PARAMETER true
add_parameter in_error_width INTEGER 6
set_parameter_property in_error_width DEFAULT_VALUE 6
set_parameter_property in_error_width DISPLAY_NAME in_error_width
set_parameter_property in_error_width TYPE INTEGER
set_parameter_property in_error_width UNITS None
set_parameter_property in_error_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property in_error_width AFFECTS_GENERATION false
set_parameter_property in_error_width HDL_PARAMETER true
add_parameter out_error_width INTEGER 1
set_parameter_property out_error_width DEFAULT_VALUE 1
set_parameter_property out_error_width DISPLAY_NAME out_error_width
set_parameter_property out_error_width TYPE INTEGER
set_parameter_property out_error_width UNITS None
set_parameter_property out_error_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property out_error_width AFFECTS_GENERATION false
set_parameter_property out_error_width HDL_PARAMETER true
add_parameter empty_width INTEGER 2
set_parameter_property empty_width DEFAULT_VALUE 2
set_parameter_property empty_width DISPLAY_NAME empty_width
set_parameter_property empty_width TYPE INTEGER
set_parameter_property empty_width UNITS None
set_parameter_property empty_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property empty_width AFFECTS_GENERATION false
set_parameter_property empty_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset clk clk Input 1


# 
# connection point clock_reset_reset
# 
add_interface clock_reset_reset reset end
set_interface_property clock_reset_reset associatedClock clock_reset
set_interface_property clock_reset_reset synchronousEdges DEASSERT
set_interface_property clock_reset_reset ENABLED true
set_interface_property clock_reset_reset EXPORT_OF ""
set_interface_property clock_reset_reset PORT_NAME_MAP ""
set_interface_property clock_reset_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset_reset reset_n reset_n Input 1


# 
# connection point in
# 
add_interface in avalon_streaming end
set_interface_property in associatedClock clock_reset
set_interface_property in associatedReset clock_reset_reset
set_interface_property in dataBitsPerSymbol 8
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits true
set_interface_property in maxChannel 0
set_interface_property in readyLatency 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in asi_in_data data Input data_width
add_interface_port in asi_in_ready ready Output 1
add_interface_port in asi_in_valid valid Input 1
add_interface_port in asi_in_error error Input in_error_width
add_interface_port in asi_in_startofpacket startofpacket Input 1
add_interface_port in asi_in_endofpacket endofpacket Input 1
add_interface_port in asi_in_empty empty Input empty_width


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clock_reset
set_interface_property out associatedReset clock_reset_reset
set_interface_property out dataBitsPerSymbol 8
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out aso_out_data data Output data_width
add_interface_port out aso_out_ready ready Input 1
add_interface_port out aso_out_valid valid Output 1
add_interface_port out aso_out_error error Output out_error_width
add_interface_port out aso_out_startofpacket startofpacket Output 1
add_interface_port out aso_out_endofpacket endofpacket Output 1
add_interface_port out aso_out_empty empty Output empty_width

