# TCL File Generated by Component Editor 18.1
# Sat May 09 15:56:17 CEST 2020
# DO NOT MODIFY


# 
# eth_tx "eth_tx" v1.0
#  2020.05.09.15:56:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module eth_tx
# 
set_module_property DESCRIPTION ""
set_module_property NAME eth_tx
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME eth_tx
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL eth_tx
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file eth_tx.v VERILOG PATH ../../../src/eth_tx.v TOP_LEVEL_FILE
add_fileset_file eth_tx_scheduler.v VERILOG PATH ../../../src/eth_tx_scheduler.v
add_fileset_file FIFO_v.v VERILOG PATH ../../../src/FIFO_v.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point transmit
# 
add_interface transmit avalon_streaming start
set_interface_property transmit associatedClock clock
set_interface_property transmit associatedReset reset_sink
set_interface_property transmit dataBitsPerSymbol 8
set_interface_property transmit errorDescriptor ""
set_interface_property transmit firstSymbolInHighOrderBits true
set_interface_property transmit maxChannel 0
set_interface_property transmit readyLatency 0
set_interface_property transmit ENABLED true
set_interface_property transmit EXPORT_OF ""
set_interface_property transmit PORT_NAME_MAP ""
set_interface_property transmit CMSIS_SVD_VARIABLES ""
set_interface_property transmit SVD_ADDRESS_GROUP ""

add_interface_port transmit data data Output 32
add_interface_port transmit endofpacket endofpacket Output 1
add_interface_port transmit error error Output 1
add_interface_port transmit ready ready Input 1
add_interface_port transmit startofpacket startofpacket Output 1
add_interface_port transmit wren valid Output 1
add_interface_port transmit mod empty Output 2


# 
# connection point rx_tx
# 
add_interface rx_tx conduit end
set_interface_property rx_tx associatedClock clock
set_interface_property rx_tx associatedReset reset_sink
set_interface_property rx_tx ENABLED true
set_interface_property rx_tx EXPORT_OF ""
set_interface_property rx_tx PORT_NAME_MAP ""
set_interface_property rx_tx CMSIS_SVD_VARIABLES ""
set_interface_property rx_tx SVD_ADDRESS_GROUP ""

add_interface_port rx_tx host_mac host_mac Input 48
add_interface_port rx_tx rx_error rx_error Input 8


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point tx_mac_misc_connection
# 
add_interface tx_mac_misc_connection conduit end
set_interface_property tx_mac_misc_connection associatedClock clock
set_interface_property tx_mac_misc_connection associatedReset reset_sink
set_interface_property tx_mac_misc_connection ENABLED true
set_interface_property tx_mac_misc_connection EXPORT_OF ""
set_interface_property tx_mac_misc_connection PORT_NAME_MAP ""
set_interface_property tx_mac_misc_connection CMSIS_SVD_VARIABLES ""
set_interface_property tx_mac_misc_connection SVD_ADDRESS_GROUP ""

add_interface_port tx_mac_misc_connection crc_fwd ff_tx_crc_fwd Output 1
add_interface_port tx_mac_misc_connection septy ff_tx_septy Input 1
add_interface_port tx_mac_misc_connection uflow ff_tx_uflow Input 1
add_interface_port tx_mac_misc_connection a_full ff_tx_a_full Input 1
add_interface_port tx_mac_misc_connection a_empty ff_tx_a_empty Input 1


# 
# connection point mpu_tx
# 
add_interface mpu_tx conduit end
set_interface_property mpu_tx associatedClock clock
set_interface_property mpu_tx associatedReset reset_sink
set_interface_property mpu_tx ENABLED true
set_interface_property mpu_tx EXPORT_OF ""
set_interface_property mpu_tx PORT_NAME_MAP ""
set_interface_property mpu_tx CMSIS_SVD_VARIABLES ""
set_interface_property mpu_tx SVD_ADDRESS_GROUP ""

add_interface_port mpu_tx buffer_c_data buffer_c_data Input 24
add_interface_port mpu_tx buffer_c_stop buffer_c_stop Output 1
add_interface_port mpu_tx data_available data_available Input 1
add_interface_port mpu_tx dim_error dim_error Input 1
add_interface_port mpu_tx dim_x dim_x Input 8
add_interface_port mpu_tx dim_y dim_y Input 8
add_interface_port mpu_tx tx_ready tx_ready Output 1

