# TCL File Generated by Component Editor 17.1
# Mon Aug 28 10:31:32 MYT 2017
# DO NOT MODIFY


# 
# st_mux_2_to_1 "st_mux_2_to_1" v1.0
#  2017.08.28.10:31:32
# 2 to 1 st mux
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module st_mux_2_to_1
# 
set_module_property DESCRIPTION "2 to 1 st mux"
set_module_property NAME st_mux_2_to_1
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "User Logic"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME st_mux_2_to_1
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL st_mux_2_to_1
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property quartus_synth ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file st_mux_2_to_1.v VERILOG PATH ../st_mux_2_to_1.v TOP_LEVEL_FILE
add_fileset_file st_mux.v VERILOG PATH ../st_mux.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property sim_verilog ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file st_mux_2_to_1.v VERILOG PATH ../st_mux_2_to_1.v
add_fileset_file st_mux.v VERILOG PATH ../st_mux.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset clk clk Input 1


# 
# connection point clock_reset_reset
# 
add_interface clock_reset_reset reset end
set_interface_property clock_reset_reset associatedClock clock_reset
set_interface_property clock_reset_reset synchronousEdges DEASSERT
set_interface_property clock_reset_reset ENABLED true
set_interface_property clock_reset_reset EXPORT_OF ""
set_interface_property clock_reset_reset PORT_NAME_MAP ""
set_interface_property clock_reset_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset_reset reset reset Input 1


# 
# connection point control_port
# 
add_interface control_port avalon end
set_interface_property control_port addressUnits WORDS
set_interface_property control_port associatedClock clock_reset
set_interface_property control_port associatedReset clock_reset_reset
set_interface_property control_port bitsPerSymbol 8
set_interface_property control_port burstOnBurstBoundariesOnly false
set_interface_property control_port burstcountUnits WORDS
set_interface_property control_port explicitAddressSpan 0
set_interface_property control_port holdTime 0
set_interface_property control_port linewrapBursts false
set_interface_property control_port maximumPendingReadTransactions 0
set_interface_property control_port maximumPendingWriteTransactions 0
set_interface_property control_port readLatency 0
set_interface_property control_port readWaitTime 1
set_interface_property control_port setupTime 0
set_interface_property control_port timingUnits Cycles
set_interface_property control_port writeWaitTime 0
set_interface_property control_port ENABLED true
set_interface_property control_port EXPORT_OF ""
set_interface_property control_port PORT_NAME_MAP ""
set_interface_property control_port CMSIS_SVD_VARIABLES ""
set_interface_property control_port SVD_ADDRESS_GROUP ""

add_interface_port control_port avs_control_port_address address Input 8
add_interface_port control_port avs_control_port_read read Input 1
add_interface_port control_port avs_control_port_readdata readdata Output 32
add_interface_port control_port avs_control_port_write write Input 1
add_interface_port control_port avs_control_port_writedata writedata Input 32
add_interface_port control_port avs_control_port_waitrequest waitrequest Output 1
set_interface_assignment control_port embeddedsw.configuration.isFlash 0
set_interface_assignment control_port embeddedsw.configuration.isMemoryDevice false
set_interface_assignment control_port embeddedsw.configuration.isNonVolatileStorage false
set_interface_assignment control_port embeddedsw.configuration.isPrintableDevice false


# 
# connection point sink0
# 
add_interface sink0 avalon_streaming end
set_interface_property sink0 associatedClock clock_st
set_interface_property sink0 dataBitsPerSymbol 8
set_interface_property sink0 errorDescriptor ""
set_interface_property sink0 firstSymbolInHighOrderBits true
set_interface_property sink0 maxChannel 0
set_interface_property sink0 readyLatency 0
set_interface_property sink0 ENABLED true
set_interface_property sink0 EXPORT_OF ""
set_interface_property sink0 PORT_NAME_MAP ""
set_interface_property sink0 CMSIS_SVD_VARIABLES ""
set_interface_property sink0 SVD_ADDRESS_GROUP ""

add_interface_port sink0 asi_sink0_data data Input 32
add_interface_port sink0 asi_sink0_ready ready Output 1
add_interface_port sink0 asi_sink0_valid valid Input 1
add_interface_port sink0 asi_sink0_error error Input 1
add_interface_port sink0 asi_sink0_startofpacket startofpacket Input 1
add_interface_port sink0 asi_sink0_endofpacket endofpacket Input 1
add_interface_port sink0 asi_sink0_empty empty Input 2


# 
# connection point sink1
# 
add_interface sink1 avalon_streaming end
set_interface_property sink1 associatedClock clock_st
set_interface_property sink1 dataBitsPerSymbol 8
set_interface_property sink1 errorDescriptor ""
set_interface_property sink1 firstSymbolInHighOrderBits true
set_interface_property sink1 maxChannel 0
set_interface_property sink1 readyLatency 0
set_interface_property sink1 ENABLED true
set_interface_property sink1 EXPORT_OF ""
set_interface_property sink1 PORT_NAME_MAP ""
set_interface_property sink1 CMSIS_SVD_VARIABLES ""
set_interface_property sink1 SVD_ADDRESS_GROUP ""

add_interface_port sink1 asi_sink1_data data Input 32
add_interface_port sink1 asi_sink1_ready ready Output 1
add_interface_port sink1 asi_sink1_valid valid Input 1
add_interface_port sink1 asi_sink1_error error Input 1
add_interface_port sink1 asi_sink1_startofpacket startofpacket Input 1
add_interface_port sink1 asi_sink1_endofpacket endofpacket Input 1
add_interface_port sink1 asi_sink1_empty empty Input 2


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock_st
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true
set_interface_property source EXPORT_OF ""
set_interface_property source PORT_NAME_MAP ""
set_interface_property source CMSIS_SVD_VARIABLES ""
set_interface_property source SVD_ADDRESS_GROUP ""

add_interface_port source aso_source_data data Output 32
add_interface_port source aso_source_ready ready Input 1
add_interface_port source aso_source_valid valid Output 1
add_interface_port source aso_source_error error Output 1
add_interface_port source aso_source_startofpacket startofpacket Output 1
add_interface_port source aso_source_endofpacket endofpacket Output 1
add_interface_port source aso_source_empty empty Output 2


# 
# connection point clock_st
# 
add_interface clock_st clock end
set_interface_property clock_st clockRate 0
set_interface_property clock_st ENABLED true
set_interface_property clock_st EXPORT_OF ""
set_interface_property clock_st PORT_NAME_MAP ""
set_interface_property clock_st CMSIS_SVD_VARIABLES ""
set_interface_property clock_st SVD_ADDRESS_GROUP ""

